name: Ilo Flows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build Ilo
      run: go install ./...

    - name: Register Tools
      run: |
        ilo tool add go
        ilo tool add bash

    - name: Build
      run: ilo run build

    - name: Test
      run: ilo run test
