name: Ilo - Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build Ilo
      run: go install ./ilocli

    - name: Build
      run: ilocli run build

    - name: Test
      run: ilocli run test
